language: php
dist: bionic
sudo: false

# Supported PHP versions to test with.
php:
  - 7.3
  - 7.4

cache:
  directories:
    - "$HOME/.composer/cache"

install:

  # Do Composer install.
  - composer install --no-interaction

script:

  # Run PHPUnit tests.
  - composer test
