language: php
dist: trusty
sudo: false

# Supported PHP versions to test with.
php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

cache:
  directories:
    - "$HOME/.composer/cache"

install:

  # Do Composer install.
  - composer install --no-interaction

script:

  # Run PHPUnit tests.
  - composer test
