<?php

namespace Druidfi\Omen;

/**
 * Renders the static PHP source for Reader::eject()'s settings.ejected.php.
 *
 * Reuses a fully-constructed Reader (so system detection, APP_ENV resolution
 * etc. have already run) but, instead of returning the resolved config array,
 * emits equivalent PHP source that doesn't depend on the Omen library.
 */
class Ejector
{
  public function __construct(private readonly Reader $reader)
  {
  }

  public function render(): string
  {
    $parts = array_filter([
      $this->renderBanner(),
      $this->renderContractDefaults(),
      $this->renderSystemBlock(),
      $this->renderDefaults(),
      $this->renderProjectFiles(),
      $this->renderSettingsDefaults(),
      $this->renderTrustedHostPatterns(),
      $this->renderVersionGatedSettings(),
    ]);

    return "<?php\n\n" . implode("\n\n", $parts) . "\n";
  }

  private function renderBanner(): string
  {
    $system = $this->reader->getSystem();
    $system_name = $system ? get_class($system) : 'none detected';
    $now = date('c');

    return <<<PHP
/**
 * Generated by Druidfi\\Omen\\Reader::eject() on {$now}.
 * Detected system: {$system_name}
 *
 * This is a starting point, not a finished settings.php. Before using it:
 *   1. Diff it against your current settings.php and carry over anything
 *      project-specific that isn't shown here.
 *   2. Rename this file to settings.php, replacing the Reader::get()/eject()
 *      call entirely.
 *   3. Delete all.settings.php and any of dev/test/prod.settings.php that
 *      were inlined below. (local.settings.php and local.services.yml are
 *      intentionally left in place and still loaded dynamically below.)
 *   4. If all.services.yml or an env-specific *.services.yml existed, merge
 *      their contents into this project's own services.yml - the lines
 *      below only keep pointing at those files, they don't inline them.
 *   5. Run `composer remove druidfi/omen`.
 *   6. Delete this settings.ejected.php file.
 */
PHP;
  }

  private function renderContractDefaults(): string
  {
    return <<<'PHP'
$routes = [];
// Reader::setTrustedHostPatterns() always reads this straight from the
// environment, regardless of which (if any) system was detected.
$drush_options_uri = getenv('DRUSH_OPTIONS_URI') ?: '';
$system_trusted_host_patterns = [];
PHP;
  }

  private function renderSystemBlock(): string
  {
    $system = $this->reader->getSystem();

    if ($system) {
      return "// Detected system: " . get_class($system) . "\n" . $system->getEjectedCode();
    }

    return <<<'PHP'
// No hosting platform was detected when this file was generated - reverse
// proxy detection and database credentials fall back to plain env vars.
$app_env = getenv('APP_ENV') ?: 'prod';

if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
  $forwarded = array_map('trim', explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']));
  $client_ip = array_shift($forwarded);

  if ($_SERVER['REMOTE_ADDR'] !== $client_ip) {
    $settings['reverse_proxy'] = true;
    $settings['reverse_proxy_addresses'] = $forwarded ?: [$_SERVER['REMOTE_ADDR']];
    $settings['reverse_proxy_trusted_headers'] =
      \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_FOR |
      \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_HOST |
      \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_PORT |
      \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_PROTO |
      \Symfony\Component\HttpFoundation\Request::HEADER_FORWARDED;
  }
}

$databases['default']['default'] = [
  'driver' => getenv('DRUPAL_DB_DRIVER') ?: 'mysql',
  'database' => getenv('DRUPAL_DB_NAME') ?: 'drupal',
  'username' => getenv('DRUPAL_DB_USER') ?: 'drupal',
  'password' => getenv('DRUPAL_DB_PASS') ?: 'drupal',
  'host' => getenv('DRUPAL_DB_HOST') ?: 'db',
  'port' => getenv('DRUPAL_DB_PORT') ?: 3306,
  'prefix' => getenv('DRUPAL_DB_PREFIX') ?: '',
  'init_commands' => [
    'isolation_level' => 'SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED',
  ],
];

$routes = array_values(array_filter(explode(',', (string) getenv('DRUPAL_ROUTES'))));
PHP;
  }

  private function renderDefaults(): string
  {
    $dev = (new Defaults('dev'))->getDefaults();
    $test = (new Defaults('test'))->getDefaults();
    $prod = (new Defaults('prod'))->getDefaults();

    $lines = ['// Environment-specific defaults (from Druidfi\Omen\Defaults).'];

    foreach (['config', 'settings'] as $bucket) {
      foreach ($this->collectLeafPaths($dev[$bucket]) as $path) {
        $dev_value = $this->getByPath($dev[$bucket], $path);
        $test_value = $this->getByPath($test[$bucket], $path);
        $prod_value = $this->getByPath($prod[$bucket], $path);
        $target = '$' . $bucket . $this->pathToArrayAccess($path);

        if ($dev_value === $test_value && $test_value === $prod_value) {
          $lines[] = sprintf('%s = %s;', $target, $this->exportValue($dev_value));
          continue;
        }

        $arms = ["  'dev' => " . $this->exportValue($dev_value) . ','];

        if ($test_value !== $prod_value) {
          $arms[] = "  'test' => " . $this->exportValue($test_value) . ',';
        }

        $arms[] = '  default => ' . $this->exportValue($prod_value) . ',';

        $lines[] = sprintf("%s = match (\$app_env) {\n%s\n};", $target, implode("\n", $arms));
      }
    }

    return implode("\n", $lines);
  }

  private function renderProjectFiles(): string
  {
    $dir = $this->settingsDir();

    if ($dir === null) {
      return '';
    }

    $lines = [];

    if (($code = $this->readStrippedFile($dir . '/all.settings.php')) !== null) {
      $lines[] = "// Inlined from all.settings.php.\n" . $code;
    }

    foreach (['dev', 'test', 'prod'] as $env) {
      $code = $this->readStrippedFile($dir . "/{$env}.settings.php");

      if ($code !== null) {
        $lines[] = "// Inlined from {$env}.settings.php.\nif (\$app_env === '{$env}') {\n" . $this->indent($code) . "\n}";
      }
    }

    foreach (['all', 'dev', 'test', 'prod'] as $env) {
      if (is_file($dir . "/{$env}.services.yml")) {
        $lines[] = sprintf(
          "if (file_exists(\$app_root . '/' . \$site_path . '/%s')) {\n  \$settings['container_yamls'][] = \$app_root . '/' . \$site_path . '/%s';\n}",
          "{$env}.services.yml", "{$env}.services.yml"
        );
      }
    }

    // local.settings.php / local.services.yml are per-developer, gitignored
    // overrides - keep them dynamic rather than inlining/deleting them.
    $lines[] = <<<'PHP'
if (file_exists($app_root . '/' . $site_path . '/local.settings.php')) {
  include $app_root . '/' . $site_path . '/local.settings.php';
}
if (file_exists($app_root . '/' . $site_path . '/local.services.yml')) {
  $settings['container_yamls'][] = $app_root . '/' . $site_path . '/local.services.yml';
}
PHP;

    return implode("\n\n", $lines);
  }

  private function renderSettingsDefaults(): string
  {
    $lines = [
      '// Directory/hash settings, in the same precedence Reader used: env var,',
      '// then whatever was already set above, then the built-in default.',
    ];

    foreach (Reader::DRUPAL_SETTING_DEFAULTS as $setting => $default) {
      $env = 'DRUPAL_' . strtoupper($setting);
      $lines[] = sprintf(
        "\$settings['%s'] = getenv('%s') ?: (\$settings['%s'] ?? %s);",
        $setting, $env, $setting, $this->exportValue($default)
      );
    }

    return implode("\n", $lines);
  }

  private function renderTrustedHostPatterns(): string
  {
    return <<<'PHP'
// Trusted host patterns, ported from Reader::setTrustedHostPatterns().
$settings['trusted_host_patterns'] = $settings['trusted_host_patterns'] ?? [];

foreach ($routes as $route) {
  $parsed = parse_url($route);

  if (is_array($parsed) && isset($parsed['host'])) {
    $settings['trusted_host_patterns'][] = '^' . str_replace('.', '\.', $parsed['host']) . '$';
  }
}

if ($drush_options_uri && !in_array($drush_options_uri, $routes, true)) {
  $parsed = parse_url($drush_options_uri);

  if (is_array($parsed) && isset($parsed['host'])) {
    $settings['trusted_host_patterns'][] = '^' . str_replace('.', '\.', $parsed['host']) . '$';
  }
}

if (!$drush_options_uri && !empty($routes)) {
  putenv('DRUSH_OPTIONS_URI=' . $routes[0]);
}

$settings['trusted_host_patterns'] = array_merge($settings['trusted_host_patterns'], $system_trusted_host_patterns);
PHP;
  }

  private function renderVersionGatedSettings(): string
  {
    $version = $this->reader->getDrupalVersion();
    $lines = ["// Version-gated settings, resolved once for Drupal {$version} at generation time."];

    if (version_compare($version, '10.3.0', '>=')) {
      $lines[] = "\$settings['state_cache'] = TRUE;";
    }

    if (version_compare($version, '11.4.0', '>=')) {
      $lines[] = '// @see https://www.drupal.org/node/3537128';
      $lines[] = "\$settings['enable_html5_validation'] = FALSE;";
    }

    return implode("\n", $lines);
  }

  private function settingsDir(): ?string
  {
    $root = $this->reader->getAppRoot();
    $site_path = $this->reader->getSitePath();

    if (!$root || !$site_path) {
      return null;
    }

    return rtrim($root, '/') . '/' . trim($site_path, '/');
  }

  private function readStrippedFile(string $path): ?string
  {
    if (!is_file($path)) {
      return null;
    }

    $code = file_get_contents($path);
    $code = preg_replace('/^\s*<\?php\s*/', '', $code, 1);
    $code = preg_replace('/\?>\s*$/', '', $code, 1);

    return trim($code);
  }

  private function indent(string $code, int $spaces = 2): string
  {
    $pad = str_repeat(' ', $spaces);

    return $pad . str_replace("\n", "\n" . $pad, $code);
  }

  /**
   * @return array<int, array<int, int|string>>
   */
  private function collectLeafPaths(array $array, array $prefix = []): array
  {
    $paths = [];

    foreach ($array as $key => $value) {
      $path = [...$prefix, $key];

      if (is_array($value) && !array_is_list($value)) {
        $paths = array_merge($paths, $this->collectLeafPaths($value, $path));
      }
      else {
        $paths[] = $path;
      }
    }

    return $paths;
  }

  private function getByPath(array $array, array $path): mixed
  {
    foreach ($path as $key) {
      $array = $array[$key];
    }

    return $array;
  }

  private function pathToArrayAccess(array $path): string
  {
    return implode('', array_map(static fn ($key) => '[' . var_export($key, true) . ']', $path));
  }

  /**
   * Like var_export(), but renders arrays with short [] syntax.
   */
  private function exportValue(mixed $value, int $depth = 0): string
  {
    if (!is_array($value)) {
      return var_export($value, true);
    }

    if ($value === []) {
      return '[]';
    }

    $pad = str_repeat('  ', $depth + 1);
    $is_list = array_is_list($value);
    $lines = [];

    foreach ($value as $key => $item) {
      $prefix = $is_list ? '' : var_export($key, true) . ' => ';
      $lines[] = $pad . $prefix . $this->exportValue($item, $depth + 1) . ',';
    }

    return "[\n" . implode("\n", $lines) . "\n" . str_repeat('  ', $depth) . ']';
  }
}
