<?php

namespace Druidfi\Omen;

/**
 * Renders the static PHP source for Reader::eject()'s settings.ejected.php.
 *
 * Reuses a fully-constructed Reader (so system detection, APP_ENV resolution
 * etc. have already run) but, instead of returning the resolved config array,
 * emits equivalent PHP source that doesn't depend on the Omen library.
 */
class Ejector
{
  /**
   * Files whose content is already inlined/handled elsewhere (see
   * renderProjectFiles()), so a bare include/require for one of these found
   * while scanning the real settings.php should not be duplicated.
   */
  private const KNOWN_SETTINGS_FILES = [
    'all.settings.php',
    'dev.settings.php',
    'test.settings.php',
    'prod.settings.php',
    'local.settings.php',
    'settings.ejected.php',
  ];

  public function __construct(private readonly Reader $reader)
  {
  }

  public function render(): string
  {
    [$before, $after] = $this->splitSettingsFile();

    $parts = array_filter([
      $this->renderBanner(),
      $before,
      $this->renderContractDefaults(),
      $this->renderSystemBlock(),
      $this->renderDefaults(),
      $this->renderProjectFiles(),
      $this->renderSettingsDefaults(),
      $this->renderTrustedHostPatterns(),
      $this->renderVersionGatedSettings(),
      $after,
    ]);

    // Inlined files may contain top-level `use` imports. Those are only legal
    // in the outermost scope, so hoist them all (deduplicated) to the top -
    // otherwise one from an env file would end up inside `if ($app_env ...)`.
    $uses = [];

    foreach ($parts as $i => $part) {
      $parts[$i] = preg_replace_callback('/^[ \t]*use\s+(?:function\s+|const\s+)?\\\\?[A-Za-z_][^;{(]*;[ \t]*\n?/m', static function (array $m) use (&$uses) {
        $uses[trim($m[0])] = trim($m[0]);

        return '';
      }, $part);
    }

    if ($uses !== []) {
      array_splice($parts, 1, 0, [implode("\n", $uses)]);
    }

    return "<?php\n\n" . implode("\n\n", array_map('trim', array_filter($parts, static fn ($part) => trim($part) !== ''))) . "\n";
  }

  private function renderBanner(): string
  {
    $system = $this->reader->getSystem();
    $system_name = $system ? get_class($system) : 'none detected';
    $now = date('c');

    return <<<PHP
/**
 * Generated by Druidfi\\Omen\\Reader::eject() on {$now}.
 * Detected system: {$system_name}
 *
 * This is a starting point, not a finished settings.php. Before using it:
 *   1. Diff it against your current settings.php and carry over anything
 *      project-specific that isn't shown here.
 *   2. Rename this file to settings.php, replacing the old one (and with it
 *      the Reader::get()/eject() call) entirely.
 *   3. Delete all.settings.php and any of dev/test/prod.settings.php that
 *      were inlined below. (local.settings.php and local.services.yml are
 *      intentionally left in place and still loaded dynamically below.)
 *   4. Keep any all/dev/test/prod.services.yml files - the lines below
 *      still load them (env-specific ones only for the matching \$app_env),
 *      they don't inline them.
 *   5. Run `composer remove druidfi/omen`.
 *
 * Any code settings.php had before/after the Reader::get()/eject() call was
 * carried forward verbatim at the very top/bottom of this file, preserving
 * the order it ran in relative to Omen. Top-level `use` imports from all
 * inlined files were hoisted to just below this comment.
 */
PHP;
  }

  private function renderContractDefaults(): string
  {
    return <<<'PHP'
// Handle HTTPS behind a TLS-terminating proxy.
if (getenv('HTTPS') !== 'on' && getenv('HTTP_X_FORWARDED_PROTO') === 'https') {
  $_SERVER['HTTPS'] = 'on';
  $_SERVER['SERVER_PORT'] = getenv('HTTP_X_FORWARDED_PORT') ?: 443;
}

$routes = [];
// Reader::setTrustedHostPatterns() always reads this straight from the
// environment, regardless of which (if any) system was detected.
$drush_options_uri = getenv('DRUSH_OPTIONS_URI') ?: '';
$system_trusted_host_patterns = [];
PHP;
  }

  private function renderSystemBlock(): string
  {
    $system = $this->reader->getSystem();

    if ($system) {
      return "// Detected system: " . get_class($system) . "\n" . $system->getEjectedCode();
    }

    return <<<'PHP'
// No hosting platform was detected when this file was generated - reverse
// proxy detection and database credentials fall back to plain env vars.
$app_env = getenv('APP_ENV') ?: 'prod';

if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
  $forwarded = array_map('trim', explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']));
  $client_ip = array_shift($forwarded);

  if ($_SERVER['REMOTE_ADDR'] !== $client_ip) {
    $settings['reverse_proxy'] = true;
    $settings['reverse_proxy_addresses'] = $forwarded ?: [$_SERVER['REMOTE_ADDR']];
    $settings['reverse_proxy_trusted_headers'] =
      \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_FOR |
      \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_HOST |
      \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_PORT |
      \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_PROTO |
      \Symfony\Component\HttpFoundation\Request::HEADER_FORWARDED;
  }
}

$databases['default']['default'] = [
  'driver' => getenv('DRUPAL_DB_DRIVER') ?: 'mysql',
  'database' => getenv('DRUPAL_DB_NAME') ?: 'drupal',
  'username' => getenv('DRUPAL_DB_USER') ?: 'drupal',
  'password' => getenv('DRUPAL_DB_PASS') ?: 'drupal',
  'host' => getenv('DRUPAL_DB_HOST') ?: 'db',
  'port' => getenv('DRUPAL_DB_PORT') ?: 3306,
  'prefix' => getenv('DRUPAL_DB_PREFIX') ?: '',
  'init_commands' => [
    'isolation_level' => 'SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED',
  ],
];

$routes = array_values(array_filter(explode(',', (string) getenv('DRUPAL_ROUTES'))));
PHP;
  }

  private function renderDefaults(): string
  {
    $envs = [];

    foreach (['dev', 'test', 'prod'] as $env) {
      $envs[$env] = (new Defaults($env))->getDefaults();
    }

    // What Defaults yields for any other APP_ENV value (e.g. 'stage'), so the
    // match() default arm stays faithful for those too.
    $other = (new Defaults(''))->getDefaults();

    $lines = ['// Environment-specific defaults (from Druidfi\Omen\Defaults).'];

    foreach (['config', 'settings'] as $bucket) {
      foreach ($this->collectLeafPaths($other[$bucket]) as $path) {
        $fallback = $this->getByPath($other[$bucket], $path);
        $target = '$' . $bucket . $this->pathToArrayAccess($path);
        $arms = [];

        foreach ($envs as $env => $defaults) {
          $value = $this->getByPath($defaults[$bucket], $path);

          if ($value !== $fallback) {
            $arms[] = "  '{$env}' => " . $this->exportValue($value) . ',';
          }
        }

        if ($arms === []) {
          $lines[] = sprintf('%s = %s;', $target, $this->exportValue($fallback));
          continue;
        }

        $arms[] = '  default => ' . $this->exportValue($fallback) . ',';

        $lines[] = sprintf("%s = match (\$app_env) {\n%s\n};", $target, implode("\n", $arms));
      }
    }

    return implode("\n", $lines);
  }

  private function renderProjectFiles(): string
  {
    $dir = $this->settingsDir();

    if ($dir === null) {
      return '';
    }

    $lines = [];

    if (($code = $this->readStrippedFile($dir . '/all.settings.php')) !== null) {
      $lines[] = "// Inlined from all.settings.php.\n" . $this->databasesNote($code) . $code;
    }

    foreach (['dev', 'test', 'prod'] as $env) {
      $code = $this->readStrippedFile($dir . "/{$env}.settings.php");

      if ($code !== null) {
        $lines[] = "// Inlined from {$env}.settings.php.\n" . $this->databasesNote($code) . "if (\$app_env === '{$env}') {\n" . $this->indent($code) . "\n}";
      }
    }

    // Reader only loads all.services.yml and the one matching APP_ENV.
    foreach (['all', 'dev', 'test', 'prod'] as $env) {
      if (is_file($dir . "/{$env}.services.yml")) {
        $line = sprintf("\$settings['container_yamls'][] = \$app_root . '/' . \$site_path . '/%s';", "{$env}.services.yml");
        $lines[] = $env === 'all' ? $line : "if (\$app_env === '{$env}') {\n  {$line}\n}";
      }
    }

    // local.settings.php / local.services.yml are per-developer, gitignored
    // overrides - keep them dynamic rather than inlining/deleting them.
    $lines[] = <<<'PHP'
if (file_exists($app_root . '/' . $site_path . '/local.settings.php')) {
  include $app_root . '/' . $site_path . '/local.settings.php';
}
if (file_exists($app_root . '/' . $site_path . '/local.services.yml')) {
  $settings['container_yamls'][] = $app_root . '/' . $site_path . '/local.services.yml';
}
PHP;

    return implode("\n\n", $lines);
  }

  /**
   * Reader::setDatabaseConnection() runs after the project files are loaded
   * and replaces $databases['default']['default'] wholesale, so anything they
   * set there was silently discarded by Omen. The ejected file sets the
   * connection first, so such lines now take effect - flag that change.
   */
  private function databasesNote(string $code): string
  {
    if (!preg_match('/\$databases\b/', $code)) {
      return '';
    }

    return "// NOTE: With Omen, Reader::get() replaced \$databases['default']['default']\n"
      . "// after loading this file, so any \$databases changes below had NO effect\n"
      . "// before ejecting. They take effect now - verify they are still correct.\n";
  }

  /**
   * Splits the real settings.php around its Reader::get()/eject() call, so
   * project code there (e.g. `include 'valkey.settings.php';`, per-platform
   * overrides) can be carried forward in the same position relative to the
   * Omen-generated code. The `//` comment block directly above the call
   * (Omen's own boilerplate) and comment-only chunks are dropped.
   *
   * @return array{0: string, 1: string}
   *   Code before and after the call. Empty strings if there's no call.
   */
  private function splitSettingsFile(): array
  {
    $dir = $this->settingsDir();

    if ($dir === null || ($code = $this->readStrippedFile($dir . '/settings.php')) === null) {
      return ['', ''];
    }

    $chunks = preg_split('/(?:^[ \t]*\/\/[^\n]*\n)*^[^\n]*\bReader::(?:get|eject)\s*\([^;]*;[^\n]*\n?/m', $code, 2);

    if (count($chunks) !== 2) {
      return ['', ''];
    }

    return array_map(function (string $chunk): string {
      // Imports of Omen itself are no longer valid once it's removed.
      $chunk = preg_replace('/^use\s+Druidfi\\\\Omen\\\\[^;]*;[ \t]*\n?/m', '', $chunk);

      // Files Ejector already inlines (or keeps loading) itself.
      $known = implode('|', array_map('preg_quote', self::KNOWN_SETTINGS_FILES));
      $chunk = preg_replace('/^[ \t]*(?:include|include_once|require|require_once)\b[^;]*[\'"\/](?:' . $known . ')[\'"]\s*\)?\s*;[ \t]*\n?/m', '', $chunk);

      return $this->hasCode($chunk) ? trim($chunk) : '';
    }, $chunks);
  }

  private function hasCode(string $chunk): bool
  {
    foreach (token_get_all('<?php ' . $chunk) as $token) {
      if (is_array($token) && in_array($token[0], [T_OPEN_TAG, T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true)) {
        continue;
      }

      return true;
    }

    return false;
  }
  private function renderSettingsDefaults(): string
  {
    $lines = [
      '// Directory/hash settings, in the same precedence Reader used: env var,',
      '// then whatever was already set above, then the built-in default.',
    ];

    foreach (Reader::DRUPAL_SETTING_DEFAULTS as $setting => $default) {
      $env = 'DRUPAL_' . strtoupper($setting);
      $lines[] = sprintf(
        "\$settings['%s'] = getenv('%s') ?: (\$settings['%s'] ?? %s);",
        $setting, $env, $setting, $this->exportValue($default)
      );
    }

    return implode("\n", $lines);
  }

  private function renderTrustedHostPatterns(): string
  {
    return <<<'PHP'
// Trusted host patterns, ported from Reader::setTrustedHostPatterns().
$settings['trusted_host_patterns'] = $settings['trusted_host_patterns'] ?? [];

foreach ($routes as $route) {
  $parsed = parse_url($route);

  if (is_array($parsed) && isset($parsed['host'])) {
    $settings['trusted_host_patterns'][] = '^' . str_replace('.', '\.', $parsed['host']) . '$';
  }
}

if ($drush_options_uri && !in_array($drush_options_uri, $routes, true)) {
  $parsed = parse_url($drush_options_uri);

  if (is_array($parsed) && isset($parsed['host'])) {
    $settings['trusted_host_patterns'][] = '^' . str_replace('.', '\.', $parsed['host']) . '$';
  }
}

if (!$drush_options_uri && !empty($routes)) {
  putenv('DRUSH_OPTIONS_URI=' . $routes[0]);
}

$settings['trusted_host_patterns'] = array_merge($settings['trusted_host_patterns'], $system_trusted_host_patterns);
PHP;
  }

  private function renderVersionGatedSettings(): string
  {
    $version = $this->reader->getDrupalVersion();
    $lines = ["// Version-gated settings, resolved once for Drupal {$version} at generation time."];

    if (version_compare($version, '10.3.0', '>=')) {
      $lines[] = "\$settings['state_cache'] = TRUE;";
    }

    if (version_compare($version, '11.4.0', '>=')) {
      $lines[] = '// @see https://www.drupal.org/node/3537128';
      $lines[] = "\$settings['enable_html5_validation'] = FALSE;";
    }

    return implode("\n", $lines);
  }

  private function settingsDir(): ?string
  {
    $root = $this->reader->getAppRoot();
    $site_path = $this->reader->getSitePath();

    if (!$root || !$site_path) {
      return null;
    }

    return rtrim($root, '/') . '/' . trim($site_path, '/');
  }

  private function readStrippedFile(string $path): ?string
  {
    if (!is_file($path)) {
      return null;
    }

    $code = file_get_contents($path);
    $code = preg_replace('/^\s*<\?php\s*/', '', $code, 1);
    $code = preg_replace('/\?>\s*$/', '', $code, 1);

    return trim($code);
  }

  private function indent(string $code, int $spaces = 2): string
  {
    $pad = str_repeat(' ', $spaces);

    return $pad . str_replace("\n", "\n" . $pad, $code);
  }

  /**
   * @return array<int, array<int, int|string>>
   */
  private function collectLeafPaths(array $array, array $prefix = []): array
  {
    $paths = [];

    foreach ($array as $key => $value) {
      $path = [...$prefix, $key];

      if (is_array($value) && !array_is_list($value)) {
        $paths = array_merge($paths, $this->collectLeafPaths($value, $path));
      }
      else {
        $paths[] = $path;
      }
    }

    return $paths;
  }

  private function getByPath(array $array, array $path): mixed
  {
    foreach ($path as $key) {
      $array = $array[$key];
    }

    return $array;
  }

  private function pathToArrayAccess(array $path): string
  {
    return implode('', array_map(static fn ($key) => '[' . var_export($key, true) . ']', $path));
  }

  /**
   * Like var_export(), but renders arrays with short [] syntax.
   */
  private function exportValue(mixed $value, int $depth = 0): string
  {
    if (!is_array($value)) {
      return var_export($value, true);
    }

    if ($value === []) {
      return '[]';
    }

    $pad = str_repeat('  ', $depth + 1);
    $is_list = array_is_list($value);
    $lines = [];

    foreach ($value as $key => $item) {
      $prefix = $is_list ? '' : var_export($key, true) . ' => ';
      $lines[] = $pad . $prefix . $this->exportValue($item, $depth + 1) . ',';
    }

    return "[\n" . implode("\n", $lines) . "\n" . str_repeat('  ', $depth) . ']';
  }
}
